spring:
  application:
    name: minimal-auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-auth}:${DB_PORT:5433}/${DB_NAME:auth_service_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
server:
  port: 8001
